package moonlightbay.compiler;

import java.util.*;
import moonlightbay.compiler.CLikeParser.ASTNode;

public class BytecodeGenerator {

    private StringBuilder output;
    private int tempVarCounter;
    private int labelCounter;
    private Map<String, String> variableMap;
    private Map<String, String> labelMap;

    public BytecodeGenerator() {
        tempVarCounter = 0;
        labelCounter = 0;
        variableMap = new HashMap<>();
        labelMap = new HashMap<>();
    }

    public String generate(ASTNode ast) {
        output = new StringBuilder();
        tempVarCounter = 0;
        labelCounter = 0;
        variableMap.clear();
        labelMap.clear();

        if (ast == null || ast.children == null) {
            return "";
        }

        // 生成指令前缀
        output.append("# Generated by Moonlight Bay MLog Optimizer\n");
        output.append("# Source: compiled from C-like syntax\n\n");

        for (ASTNode node : ast.children) {
            generateNode(node);
        }

        return output.toString();
    }

    private void generateNode(ASTNode node) {
        if (node == null) return;

        switch (node.type) {
            case "assignment":
                generateAssignment(node);
                break;
            case "declaration":
                generateDeclaration(node);
                break;
            case "if":
                generateIf(node);
                break;
            case "while":
                generateWhile(node);
                break;
            case "for":
                generateFor(node);
                break;
            case "print":
                generatePrint(node);
                break;
            case "sensor":
                generateSensor(node);
                break;
            case "control":
                generateControl(node);
                break;
            case "operation":
                generateOperation(node);
                break;
            case "block":
                generateBlock(node);
                break;
            default:
                output
                    .append("# Unknown node type: ")
                    .append(node.type)
                    .append("\n");
        }
    }

    private void generateAssignment(ASTNode node) {
        String target = (String) node.properties.get("target");
        String value = (String) node.properties.get("value");

        // 检查是否是表达式
        if (isExpression(value)) {
            String tempVar = getTempVar();
            generateExpression(value, tempVar);
            output
                .append("set ")
                .append(target)
                .append(" ")
                .append(tempVar)
                .append("\n");
        } else {
            output
                .append("set ")
                .append(target)
                .append(" ")
                .append(value)
                .append("\n");
        }
    }

    private void generateDeclaration(ASTNode node) {
        String type = (String) node.properties.get("type");
        String name = (String) node.properties.get("name");
        String initializer = (String) node.properties.get("initializer");

        // 记录变量类型
        variableMap.put(name, type);

        if (initializer != null) {
            if (isExpression(initializer)) {
                String tempVar = getTempVar();
                generateExpression(initializer, tempVar);
                output
                    .append("set ")
                    .append(name)
                    .append(" ")
                    .append(tempVar)
                    .append("\n");
            } else {
                output
                    .append("set ")
                    .append(name)
                    .append(" ")
                    .append(initializer)
                    .append("\n");
            }
        } else {
            output.append("set ").append(name).append(" 0\n");
        }
    }

    private void generateIf(ASTNode node) {
        String condition = (String) node.properties.get("condition");
        String condVar = getTempVar();

        generateCondition(condition, condVar);

        String endLabel = getLabel("endif");

        output
            .append("jump ")
            .append(endLabel)
            .append(" equal ")
            .append(condVar)
            .append(" 0\n");

        // then分支
        if (!node.children.isEmpty()) {
            generateNode(node.children.get(0));
        }

        // else分支
        if (node.children.size() > 1) {
            String elseLabel = getLabel("else");
            output.append("jump ").append(elseLabel).append(" always\n");
            output.append(endLabel).append(":\n");
            generateNode(node.children.get(1));
            output.append(elseLabel).append(":\n");
        } else {
            output.append(endLabel).append(":\n");
        }
    }

    private void generateWhile(ASTNode node) {
        String condition = (String) node.properties.get("condition");
        String condVar = getTempVar();

        String startLabel = getLabel("while");
        String endLabel = getLabel("endwhile");

        output.append(startLabel).append(":\n");
        generateCondition(condition, condVar);
        output
            .append("jump ")
            .append(endLabel)
            .append(" equal ")
            .append(condVar)
            .append(" 0\n");

        if (!node.children.isEmpty()) {
            generateNode(node.children.get(0));
        }

        output.append("jump ").append(startLabel).append(" always\n");
        output.append(endLabel).append(":\n");
    }

    private void generateFor(ASTNode node) {
        // for循环转换为while循环
        // 初始化
        if (!node.children.isEmpty() && node.children.get(0) != null) {
            generateNode(node.children.get(0));
        }

        String condition = (String) node.properties.get("condition");
        String condVar = getTempVar();

        String startLabel = getLabel("for");
        String endLabel = getLabel("endfor");

        output.append(startLabel).append(":\n");
        generateCondition(condition, condVar);
        output
            .append("jump ")
            .append(endLabel)
            .append(" equal ")
            .append(condVar)
            .append(" 0\n");

        // 循环体
        if (node.children.size() > 1) {
            generateNode(node.children.get(1));
        }

        // 增量
        if (node.children.size() > 2 && node.children.get(2) != null) {
            generateNode(node.children.get(2));
        }

        output.append("jump ").append(startLabel).append(" always\n");
        output.append(endLabel).append(":\n");
    }

    private void generatePrint(ASTNode node) {
        String content = (String) node.properties.get("content");

        // 处理多个参数
        String[] parts = content.split(",");
        for (String part : parts) {
            output.append("print ").append(part.trim()).append("\n");
        }
        output.append("printflush message1\n");
    }

    private void generateSensor(ASTNode node) {
        String result = (String) node.properties.get("result");
        String entity = (String) node.properties.get("entity");
        String property = (String) node.properties.get("property");

        output
            .append("sensor ")
            .append(result)
            .append(" ")
            .append(entity)
            .append(" ")
            .append(property)
            .append("\n");
    }

    private void generateControl(ASTNode node) {
        String command = (String) node.properties.get("command");
        @SuppressWarnings("unchecked")
        List<String> args = (List<String>) node.properties.get("args");

        output.append("control ").append(command);
        for (String arg : args) {
            output.append(" ").append(arg);
        }
        output.append("\n");
    }

    private void generateOperation(ASTNode node) {
        String result = (String) node.properties.get("result");
        String operator = (String) node.properties.get("operator");
        String a = (String) node.properties.get("a");
        String b = (String) node.properties.get("b");

        // 映射运算符
        String mlogOp = mapOperator(operator);
        output
            .append("op ")
            .append(mlogOp)
            .append(" ")
            .append(result)
            .append(" ")
            .append(a)
            .append(" ")
            .append(b)
            .append("\n");
    }

    private void generateBlock(ASTNode node) {
        for (ASTNode child : node.children) {
            generateNode(child);
        }
    }

    private void generateExpression(String expr, String resultVar) {
        expr = expr.trim();

        // 支持运算符优先级
        if (expr.contains("+")) {
            String[] parts = splitByOperator(expr, '+');
            if (parts.length == 2) {
                generateExpression(parts[0], resultVar);
                String temp = getTempVar();
                generateExpression(parts[1], temp);
                output
                    .append("op add ")
                    .append(resultVar)
                    .append(" ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp)
                    .append("\n");
            }
        } else if (expr.contains("-")) {
            String[] parts = splitByOperator(expr, '-');
            if (parts.length == 2) {
                generateExpression(parts[0], resultVar);
                String temp = getTempVar();
                generateExpression(parts[1], temp);
                output
                    .append("op sub ")
                    .append(resultVar)
                    .append(" ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp)
                    .append("\n");
            }
        } else if (expr.contains("*")) {
            String[] parts = splitByOperator(expr, '*');
            if (parts.length == 2) {
                generateExpression(parts[0], resultVar);
                String temp = getTempVar();
                generateExpression(parts[1], temp);
                output
                    .append("op mul ")
                    .append(resultVar)
                    .append(" ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp)
                    .append("\n");
            }
        } else if (expr.contains("/")) {
            String[] parts = splitByOperator(expr, '/');
            if (parts.length == 2) {
                generateExpression(parts[0], resultVar);
                String temp = getTempVar();
                generateExpression(parts[1], temp);
                output
                    .append("op div ")
                    .append(resultVar)
                    .append(" ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp)
                    .append("\n");
            }
        } else if (expr.contains("%")) {
            String[] parts = splitByOperator(expr, '%');
            if (parts.length == 2) {
                generateExpression(parts[0], resultVar);
                String temp = getTempVar();
                generateExpression(parts[1], temp);
                output
                    .append("op mod ")
                    .append(resultVar)
                    .append(" ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp)
                    .append("\n");
            }
        } else {
            // 基本值
            output
                .append("set ")
                .append(resultVar)
                .append(" ")
                .append(expr)
                .append("\n");
        }
    }

    private void generateCondition(String condition, String resultVar) {
        condition = condition.trim();

        if (condition.contains("==")) {
            String[] parts = splitByOperator(condition, "==");
            if (parts.length == 2) {
                output
                    .append("op equal ")
                    .append(resultVar)
                    .append(" ")
                    .append(parts[0].trim())
                    .append(" ")
                    .append(parts[1].trim())
                    .append("\n");
            }
        } else if (condition.contains("!=")) {
            String[] parts = splitByOperator(condition, "!=");
            if (parts.length == 2) {
                output
                    .append("op notEqual ")
                    .append(resultVar)
                    .append(" ")
                    .append(parts[0].trim())
                    .append(" ")
                    .append(parts[1].trim())
                    .append("\n");
            }
        } else if (condition.contains(">=")) {
            String[] parts = splitByOperator(condition, ">=");
            if (parts.length == 2) {
                output
                    .append("op greaterThanEq ")
                    .append(resultVar)
                    .append(" ")
                    .append(parts[0].trim())
                    .append(" ")
                    .append(parts[1].trim())
                    .append("\n");
            }
        } else if (condition.contains("<=")) {
            String[] parts = splitByOperator(condition, "<=");
            if (parts.length == 2) {
                output
                    .append("op lessThanEq ")
                    .append(resultVar)
                    .append(" ")
                    .append(parts[0].trim())
                    .append(" ")
                    .append(parts[1].trim())
                    .append("\n");
            }
        } else if (condition.contains(">")) {
            String[] parts = splitByOperator(condition, ">");
            if (parts.length == 2) {
                output
                    .append("op greaterThan ")
                    .append(resultVar)
                    .append(" ")
                    .append(parts[0].trim())
                    .append(" ")
                    .append(parts[1].trim())
                    .append("\n");
            }
        } else if (condition.contains("<")) {
            String[] parts = splitByOperator(condition, "<");
            if (parts.length == 2) {
                output
                    .append("op lessThan ")
                    .append(resultVar)
                    .append(" ")
                    .append(parts[0].trim())
                    .append(" ")
                    .append(parts[1].trim())
                    .append("\n");
            }
        } else if (condition.contains("&&")) {
            String[] parts = condition.split("&&");
            if (parts.length == 2) {
                String temp1 = getTempVar();
                String temp2 = getTempVar();
                generateCondition(parts[0].trim(), temp1);
                generateCondition(parts[1].trim(), temp2);
                output
                    .append("op and ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp1)
                    .append(" ")
                    .append(temp2)
                    .append("\n");
            }
        } else if (condition.contains("||")) {
            String[] parts = condition.split("\\|\\|");
            if (parts.length == 2) {
                String temp1 = getTempVar();
                String temp2 = getTempVar();
                generateCondition(parts[0].trim(), temp1);
                generateCondition(parts[1].trim(), temp2);
                output
                    .append("op or ")
                    .append(resultVar)
                    .append(" ")
                    .append(temp1)
                    .append(" ")
                    .append(temp2)
                    .append("\n");
            }
        } else {
            // 直接值
            output
                .append("set ")
                .append(resultVar)
                .append(" ")
                .append(condition)
                .append("\n");
        }
    }

    private boolean isExpression(String str) {
        return (
            str.contains("+") ||
            str.contains("-") ||
            str.contains("*") ||
            str.contains("/") ||
            str.contains("%") ||
            str.contains("(") ||
            str.contains(")")
        );
    }

    private String[] splitByOperator(String str, char operator) {
        int index = str.lastIndexOf(operator);
        if (index == -1) return new String[] { str };

        String left = str.substring(0, index);
        String right = str.substring(index + 1);
        return new String[] { left, right };
    }

    private String[] splitByOperator(String str, String operator) {
        int index = str.indexOf(operator);
        if (index == -1) return new String[] { str };

        String left = str.substring(0, index);
        String right = str.substring(index + operator.length());
        return new String[] { left, right };
    }

    private String mapOperator(String op) {
        switch (op) {
            case "+":
                return "add";
            case "-":
                return "sub";
            case "*":
                return "mul";
            case "/":
                return "div";
            case "%":
                return "mod";
            case "==":
                return "equal";
            case "!=":
                return "notEqual";
            case ">":
                return "greaterThan";
            case "<":
                return "lessThan";
            case ">=":
                return "greaterThanEq";
            case "<=":
                return "lessThanEq";
            case "&&":
                return "and";
            case "||":
                return "or";
            default:
                return op;
        }
    }

    private String getTempVar() {
        return "__temp" + (tempVarCounter++);
    }

    private String getLabel(String prefix) {
        return "__" + prefix + (labelCounter++);
    }
}
