buildscript {
    repositories {
        mavenCentral()
        maven { url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
        maven { url 'https://www.jitpack.io' }
    }
    dependencies {
        classpath "com.github.Anuken.Arc:arc-core:158.1"
        classpath "com.github.Anuken.Mindustry:core:158.1"
    }
}

plugins {
    id 'java'
}

sourceCompatibility = 17
targetCompatibility = 17

repositories {
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven { url 'https://www.jitpack.io' }
}

dependencies {
    compileOnly "com.github.Anuken.Arc:arc-core:158.1"
    compileOnly "com.github.Anuken.Mindustry:core:158.1"
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    from(sourceSets.main.output)
    
    manifest {
        attributes 'Main-Class': 'moonlightbay.MoonlightBayMod'
    }
}
