#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - sloppy, but assuming only one hyphen in the pattern.
    # The pattern is: -Dkey=value OR -Dkey=value with spaces after the equals.
    # Solution: split on space only if there is no '='
    # This works even with no space after =, but then the pattern will be ' -Dkey=value'
    # Example: '-Dkey=value' becomes '-Dkey' '=value'
    # The space is only added if there is a space after the =, e.g. '-Dkey= value' becomes '-Dkey' '=value' ' '
    # In this transformed string, we can split on space safely.
    # If there are no spaces, we can keep it as-is, so we keep the entire string as part of the arguments.
    # The advantage of this scheme is that it handles the case where no space at all.
    # The pattern is that the entire arguments string is either:
    # a) '-Dkey=value' (no spaces)
    # b) '-Dkey= value' (space after =)
    # c) '-Dkey=value more arguments' (space after value with more arguments)
    # Importantly, the regex will capture the part after the last '= ' (if any) as the value.
    # This detection is for transforming the arguments, and the case where suppose there is an actual
    # space character in the value is rare (supports file path with spaces).
    # The end result is that the transformed arguments array will have ' -Dkey' and 'value' and ' '
    # and we can split on the space only.
    #
    # Better approach: While IFS= read -r line; do
    #                 if [[ $line == '-D'*'='* ]]; then
    #                     key=${line%%=*}
    #                     value=${line#*=}
    #                     if [[ $value == *' '* ]]; then
    #                         # There is a space, so we need to quote the value
    #                         printf '%s\n' "$key" "$value"
    #                     else
    #                         printf '%s\n' "$line"
    #                     fi
    #                 else
    #                     printf '%s\n' "$line"
    #                 fi
    #             done

    # This will read the arguments one line at a time and transform them.
    # We'll use a simpler approach: read the entire args string and transform it.
    # We'll use a custom function to transform the arguments.
    # This function will transform the arguments string into a short argument list.
    # It does this by first splitting the string into a list of chars and then only adding the '\0' to the list if it sees the
    # pattern '-Dkey=value' or '-Dkey= value', else if the pattern is any other short argument it will append it as is.
    # This will result in a string that the shell can split safely.
    transform_short_arguments() {
        for token; do
            case $token in
                -D*)
                    # Extract the value part after the last '='
                    value=${token##*=}
                    # Extract the key part before the first '='
                    key=${token%%=*}
                    # If there is a '=value' part and it does not contain a space, then we need to split it.
                    if [ "$key" != "$token" ] && [ -n "${value##* }" ]; then
                        # There is a '=value' part, but it might have spaces, so we need to split on space? Unlikely.
                        printf '%s\n' "$key" "$value"
                    else
                        # No '=value' part, or the value has spaces, so we keep as is.
                        # Or the token has no '=', e.g. just '-D', which is invalid.
                        # Or the token is a short argument that is not '-D'.
                        printf '%s\n' "$token"
                    fi
                    ;;
                *)
                    printf '%s\n' "$token"
                    ;;
            esac
        done
    }

    # Now we can split the arguments safely.
    IFS=" " read -r -a args <<< "$(transform_short_arguments "$@")"
else
    args=("$@")
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args, replace newlines in the quotes with a special sequence, and
# then use "while read" to read the arg line by line and join them with newlines.
# This is a bit hacky, but it's a POSIX way to parse quoted args with newlines.
printf '%s\n' "$@" | xargs -n1 printf '%s\n' | while IFS= read -r arg; do
    # If the argument starts with a quote, then we need to read until closing quote.
    # This is a simple state machine that handles single and double quotes.
    # The state is stored in the variable 'state'. It is either 0 (not in quotes), 1 (in single quotes), or 2 (in double quotes).
    # The variable 'buffer' accumulates the argument.
    # The variable 'escape' is used to handle escape characters.
    # The variable 'line' is used to store the current line.
    # The loop reads characters one by one.
    # This is a bit of a hack, but it's a POSIX way to parse quotes.
    # The alternative would be to use a more sophisticated tool, but we want to keep this script simple.
    # This function will parse a single line (argument) that may contain quotes.
    # It will output the parsed argument (unescaped) to stdout.
    parse_quotes() {
        argument="$1"
        len="${#argument}"
        state=0
        escape=0
        buffer=""
        i=0
        while [ $i -lt $len ]; do
            char="${argument:$i:1}"
            if [ $escape -eq 1 ]; then
                buffer="$buffer$char"
                escape=0
                i=$((i+1))
                continue
            fi
            case $char in
                '\\')
                    escape=1
                    ;;
                "'")
                    if [ $state -eq 0 ]; then
                        state=1
                    elif [ $state -eq 1 ]; then
                        state=0
                    else
                        buffer="$buffer'"
                    fi
                    ;;
                '"')
                    if [ $state -eq 0 ]; then
                        state=2
                    elif [ $state -eq 2 ]; then
                        state=0
                    else
                        buffer="$buffer\""
                    fi
                    ;;
                *)
                    buffer="$buffer$char"
                    ;;
            esac
            i=$((i+1))
        done
        printf '%s' "$buffer"
    }
    # We need to call the parse function with the current line.
    parsed=$(parse_quotes "$arg")
    printf '%s\n' "$parsed"
done | {
    # Now we have the arguments parsed, we can join them with newlines.
    # We also need to add the default JVM opts, JAVA_OPTS, and GRADLE_OPTS.
    # shellcheck disable=SC2048
    # We need to set IFS to newline to read the arguments.
    IFS='
'
    # We need to gather the arguments into a list.
    set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
    # Read the parsed arguments from stdin and add them to the list.
    while IFS= read -r arg; do
        set -- "$@" "$arg"
    done
    # Execute the java command.
    exec "$JAVACMD" "$@"
}
